apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-03-09T10:08:13Z"
  labels:
    app: myservice
  name: myservice
  namespace: default
  resourceVersion: "1805"
  uid: 8f77e8f6-cfec-4f4c-9ad3-b3a40ec297e5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.107.210.10
  clusterIPs:
  - 10.107.210.10
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30807
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: myservice
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
